# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 20
#$ -q sThM.q
#$ -l mres=200G,h_data=10G,h_vmem=10G,himem
#$ -cwd
#$ -j y
#$ -N job_01b_run_contigs_workflow
#$ -o hydra_logs/job_01b_run_contigs_workflow.log
#$ -M scottjj@si.edu
#
# ----------------Modules------------------------- #
module load gcc/4.9.2
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
### CALLING ANVIO ###
export PATH=/home/scottjj/miniconda3:$PATH
export PATH=/home/scottjj/miniconda3/bin:$PATH
source activate anvio-master

#############################################
### Making sure everything is cool ###
which python
python --version
source /home/scottjj/virtual-envs/anvio-master/bin/activate
which python
python --version
which anvi-interactive 
diamond --version 
anvi-self-test -v 
#############################################

## cog tmp
rm -r /pool/genomics/stri_istmobiome/dbs/cog_db/tmp/
mkdir -p /pool/genomics/stri_istmobiome/dbs/cog_db/tmp/

## pfam tmp
rm -r /pool/genomics/stri_istmobiome/dbs/pfam_db/tmp_data/
mkdir -p /pool/genomics/stri_istmobiome/dbs/pfam_db/tmp_data/
TMPDIR="/pool/genomics/stri_istmobiome/dbs/pfam_db/tmp_data/"

##scg
rm -r /pool/genomics/stri_istmobiome/dbs/scgs-taxonomy-data/tmp/
mkdir /pool/genomics/stri_istmobiome/dbs/scgs-taxonomy-data/tmp/


anvi-run-workflow -w contigs -c contigs-default-config.json --additional-params --jobs 20 --resources nodes=20 --keep-going --rerun-incomplete --unlock
anvi-run-workflow -w contigs -c contigs-default-config.json --additional-params --jobs 20 --resources nodes=20 --keep-going --rerun-incomplete

#mkdir /pool/genomics/stri_istmobiome/dbs/tmp/
#TMPDIR="/pool/genomics/stri_istmobiome/dbs/tmp/"

#for genome in `cat list_genomes.txt`
#do
#  echo $genome
#  anvi-run-scg-taxonomy -c 03_CONTIGS/$genome-contigs.db  -T $NSLOTS 
#  anvi-run-pfams -c 03_CONTIGS/$genome-contigs.db -T $NSLOTS --pfam-data-dir /pool/genomics/stri_istmobiome/dbs/pfam_db/
#  anvi-run-kegg-kofams -c 03_CONTIGS/$genome-contigs.db -T $NSLOTS --kegg-data-dir /pool/genomics/stri_istmobiome/dbs/kegg_kofam/
#  anvi-run-ncbi-cogs -c 03_CONTIGS/$genome-contigs.db -T $NSLOTS --cog-data-dir /pool/genomics/stri_istmobiome/dbs/cog_db/ --temporary-dir-path /pool/genomics/stri_istmobiome/dbs/cog_db/tmp/
#  anvi-run-trna-taxonomy  -c 03_CONTIGS/$genome-contigs.db -T $NSLOTS 
#  echo "----------------------"
#done




#anvi-compute-genome-similarity -f Arcobacter-fasta-rename.txt -o 04_GENOME_SIMILARITY --program fastANI -T $NSLOTS

#
echo = `date` job $JOB_NAME don


